version: '1'
services:
  stock-api:
    container_name : stock-api
    build: .
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
    ports:
      - "6060:6060"
    environment:
      SERVER_PORT: 6060
      DB_HOST: stock-db
      DB_PORT: 3306
      DB_NAME: stock_db
      DB_USERNAME: stock_db_user
      DB_PASSWORD: '*fUvfR4OZ1k7hpKM'
  stock-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin@admin
      MYSQL_DATABASE: stock_db
      MYSQL_USER: stock_db_user
      MYSQL_PASSWORD: '*fUvfR4OZ1k7hpKM'
    ports:
      - "3306:3306"
    volumes:
      - stock-data:/var/lib/mysql
volumes:
 stock-data: