import express from "express";
import morgan from "morgan";
import { employeeRoutes } from "./routes/employee.routes";
import cors from 'cors'; 
import { errMw } from "./middlewares/err.mw";
import { lookupRoutes } from "./routes/lookup.routes";
import { supplierRoutes } from "./routes/supplier.routes";
import { orderRoutes } from "./routes/order.routes";
import { orderItemRoutes } from "./routes/order-item.routes";
const app = express();
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(morgan("dev"));
app.use("/api/v1/employees", employeeRoutes);
app.use("/api/v1/lookups", lookupRoutes);
app.use("/api/v1/suppliers", supplierRoutes);
app.use("/api/v1/orders", orderRoutes);
app.use("/api/v1/order-items", orderItemRoutes);
app.use(errMw);
export default app;
